"""DuckDB runner for sql/analysis.sql. Fixed-width formatter (never
DuckDB's console renderer), so sql_report.md's bytes cannot depend on
the terminal it was generated in. Shop-side only: no truth path is
registered as a view or named anywhere in this file.
"""

import re
import sys
from pathlib import Path

import duckdb

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import config  # noqa: E402

# File-backed views: read straight from committed outputs.
FILE_VIEWS = {
    "directory": "data/public/vendor_directory.csv",
    "coverage": "outputs/coverage_matrix.csv",
    "health": "outputs/health_index.csv",
}
# In-memory views: postings_tagged / traffic_clean / spend_resolved are
# not committed as separate CSVs (they would roughly double data/exhaust's
# size to store row-level duplicates of information already reflected in
# coverage_matrix.csv and level_bands.csv). They are rebuilt here, in
# memory, from the same estimation-layer functions run_all.py's QA pass
# uses, and registered directly as DuckDB views.
VIEWS = {**FILE_VIEWS, "postings_tagged": None, "traffic_clean": None, "spend_resolved": None}


def _build_memory_views(root):
    from estimation.loader import ShopData
    from estimation import qa, tagger_mock

    shop = ShopData(root)
    final_q = config.QUARTERS[-1]
    av = shop.as_of(final_q)
    dm = shop.descriptor_map()

    deduped = qa.dedupe_jobs(av.jobs)
    postings_tagged = deduped.copy()
    if not postings_tagged.empty:
        postings_tagged["quarter"] = postings_tagged["posted_date"].map(qa._quarter_of_date)
        postings_tagged["function"] = tagger_mock.tag_titles(postings_tagged["title"])

    bridge, _ = qa.detect_descriptor_fragmentation(av.spend, dm)
    resolved = qa.resolve_spend(av.spend, dm, bridge)
    bot_final = qa.detect_bot_spikes(av.web, av.jobs, resolved)
    traffic_clean = qa.winsorize_web(av.web, bot_final)

    return {"postings_tagged": postings_tagged, "traffic_clean": traffic_clean,
            "spend_resolved": resolved}

_CUT_RE = re.compile(r"^-- @cut:\s*(\S+)\s*$", re.MULTILINE)


def _parse_cuts(sql_text: str):
    matches = list(_CUT_RE.finditer(sql_text))
    cuts = []
    for i, m in enumerate(matches):
        name = m.group(1)
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(sql_text)
        query = sql_text[start:end].strip()
        query = "\n".join(line for line in query.splitlines()
                           if not line.strip().startswith("--") or "@cut" not in line)
        cuts.append((name, query))
    return cuts


def _format_table(cols, rows) -> str:
    str_rows = [[("" if v is None else str(v)) for v in row] for row in rows]
    widths = [len(c) for c in cols]
    for row in str_rows:
        for i, v in enumerate(row):
            widths[i] = max(widths[i], len(v))
    def fmt_row(vals):
        return "  ".join(v.ljust(widths[i]) for i, v in enumerate(vals))
    lines = [fmt_row(cols), "  ".join("-" * w for w in widths)]
    for row in str_rows:
        lines.append(fmt_row(row))
    return "\n".join(lines)


def run(root=None, out_path=None) -> str:
    root = config.ROOT if root is None else Path(root)
    out_path = (config.OUTPUT_DIR / "sql_report.md") if out_path is None else out_path

    con = duckdb.connect(database=":memory:")
    # Single-threaded: DuckDB's parallel aggregation can sum floats in a
    # different order across runs, which changes the last few bits of a
    # SUM() result and breaks byte-identical reruns. Determinism here
    # matters more than the (trivial, at this data size) speed cost.
    con.execute("PRAGMA threads=1")
    for name, relpath in FILE_VIEWS.items():
        path = (root / relpath).resolve().as_posix()
        con.execute(f"CREATE VIEW {name} AS SELECT * FROM read_csv_auto('{path}', header=True)")
    for name, df in _build_memory_views(root).items():
        con.register(name, df)

    sql_text = (Path(__file__).parent / "analysis.sql").read_text(encoding="utf-8")
    cuts = _parse_cuts(sql_text)

    lines = ["# SQL report\n", "Generated by `python sql/run_sql.py` over the committed "
             "shop-side outputs. Truth is never registered as a view here.\n"]
    for name, query in cuts:
        result = con.execute(query)
        cols = [d[0] for d in result.description]
        rows = result.fetchall()
        lines.append(f"## {name}\n")
        lines.append("```")
        lines.append(_format_table(cols, rows))
        lines.append("```")
        lines.append(f"\n{len(rows)} row(s).\n")

    text = "\n".join(lines) + "\n"
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    con.close()
    return text


if __name__ == "__main__":
    run()
    print(f"wrote {config.OUTPUT_DIR / 'sql_report.md'}")
