"""Execute the analytical SQL against the panel and the estimates with DuckDB.

Registers post-QA panel views plus the estimation outputs, runs every
statement in analysis.sql, prints the results, and writes
outputs/sql_report.md so the analysis is inspectable without running
anything. This runner sits shop-side: it imports only the estimation
layer and never registers ground truth.

Tables are rendered by the fixed-width formatter below rather than by
DuckDB's console renderer, whose output depends on the detected terminal
width; the report must be byte-identical no matter where it is run, and
tests/test_determinism.py checks that it is.
"""

import sys
from pathlib import Path

import duckdb
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import config                                  # noqa: E402
from estimation import loader, methods         # noqa: E402

SQL = Path(__file__).resolve().parent / "analysis.sql"

TITLES = [
    "Cohort retention by adoption quarter (weighted, subscription services)",
    "Penetration by segment, 2024Q4 (unweighted vs weighted)",
    "Market concentration by quarter (HHI, m4 revenue)",
    "Competitive share shift (largest quarter-over-quarter moves, m4)",
    "Estimate vs reported, prior quarters (m4 revenue, public data only)",
]


def _fmt(v) -> str:
    """One cell as text, environment-independent (shortest-repr floats)."""
    if v is None:
        return "NULL"
    if isinstance(v, (bool, np.bool_)):
        return str(bool(v))
    if isinstance(v, (int, np.integer)):
        return str(int(v))
    if isinstance(v, (float, np.floating)):
        f = float(v)
        return "NaN" if f != f else repr(f)
    return str(v)


def render_table(columns, rows) -> str:
    """Plain fixed-width table: all rows, all columns, no terminal probing.

    Numeric columns are right-aligned, everything else left-aligned.
    """
    cells = [[_fmt(v) for v in row] for row in rows]
    numeric = []
    for i in range(len(columns)):
        vals = [row[i] for row in rows if row[i] is not None]
        numeric.append(bool(vals) and all(
            isinstance(v, (int, float, np.integer, np.floating))
            and not isinstance(v, (bool, np.bool_)) for v in vals))
    widths = [
        max(len(columns[i]), *(len(r[i]) for r in cells)) if cells
        else len(columns[i])
        for i in range(len(columns))]
    def line(parts, pad=" "):
        out = []
        for i, p in enumerate(parts):
            out.append(p.rjust(widths[i], pad) if numeric[i]
                       else p.ljust(widths[i], pad))
        return "| " + " | ".join(out) + " |"
    body = [line(list(columns)), line(["" for _ in columns], pad="-")]
    body += [line(r) for r in cells]
    body.append(f"{len(cells)} row{'s' if len(cells) != 1 else ''}, "
                f"{len(columns)} column{'s' if len(columns) != 1 else ''}")
    return "\n".join(body)


def build_views(con):
    shop = loader.ShopData(ROOT)
    reported = shop.reported_before(config.QUARTERS[-1])
    bundle, _, cor = methods.build_engines(
        shop.panel_transactions(), shop.panelists(), shop.companies(),
        shop.census_margins(), reported)

    txns = bundle["corrected"][["txn_id", "panelist_id", "date", "month",
                                "quarter", "company", "amount", "instrument"]]
    con.register("panel_txns", txns)
    con.register("panelists", bundle["panelists"])

    W, _ = cor.raked_weights(np.ones(cor.P))
    pids = bundle["panelists"].sort_values("panelist_id")["panelist_id"].to_numpy()
    frames = []
    for qi, q in enumerate(config.QUARTERS):
        nz = W[:, qi] > 0
        frames.append(pd.DataFrame({
            "quarter": q, "panelist_id": pids[nz], "weight": W[nz, qi]}))
    con.register("weights_q", pd.concat(frames, ignore_index=True))

    est = pd.read_csv(ROOT / "outputs" / "estimates.csv")
    con.register("estimates", est)
    con.register("reported", reported)


def build_report() -> str:
    """The full report text, deterministically rendered."""
    con = duckdb.connect()
    build_views(con)

    # strip full-line comments before splitting so a semicolon inside a
    # comment can never shear a statement in half
    sql_text = "\n".join(
        line for line in SQL.read_text(encoding="utf-8").splitlines()
        if not line.lstrip().startswith("--"))
    statements = [s.strip() for s in sql_text.split(";") if s.strip()]
    lines = ["# SQL Analysis Report", "",
             "Generated by sql/run_sql.py (DuckDB) over the post-QA panel "
             "views and outputs/estimates.csv. Ground truth is not "
             "registered; every number here is computable shop-side.", ""]
    for i, stmt in enumerate(statements):
        title = TITLES[i] if i < len(TITLES) else f"Query {i + 1}"
        rel = con.sql(stmt)
        table = render_table(rel.columns, rel.fetchall())
        lines.append(f"## {i + 1}. {title}")
        lines.append("")
        lines.append("```")
        lines.append(table)
        lines.append("```")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    report = build_report()
    print(report)
    (ROOT / "outputs" / "sql_report.md").write_text(
        report, encoding="utf-8", newline="\n")
    print("\nwrote outputs/sql_report.md")


if __name__ == "__main__":
    main()
