{{
    config(
        materialized='view'
    )
}}

/*
    Staging model for the synthetic streaming-catalog tracks

    Purpose: Clean and type-cast raw seed data
    Source: streaming_tracks_raw (seed, generated by scripts/generate_seed.py)

    Transformations:
    - Explicit type casting
    - Date parsing
    - Boolean conversion for explicit flag
    - Duration conversion to seconds
*/

with source as (
    select * from {{ ref('streaming_tracks_raw') }}
),

cleaned as (
    select
        -- Primary key
        track_id,

        -- Content dimensions
        track_name,
        artist_name,
        album_name,
        genre,
        label,
        country,

        -- Date dimension
        cast(release_date as date) as release_date,
        year(cast(release_date as date)) as release_year,

        -- Audio features (already numeric in source)
        cast(duration_ms as integer) as duration_ms,
        round(cast(duration_ms as float) / 1000, 2) as duration_seconds,
        round(cast(duration_ms as float) / 60000, 2) as duration_minutes,
        cast(popularity as integer) as popularity,
        cast(danceability as float) as danceability,
        cast(energy as float) as energy,
        cast(key as integer) as musical_key,
        cast(loudness as float) as loudness,
        cast(mode as integer) as musical_mode,
        cast(instrumentalness as float) as instrumentalness,
        cast(tempo as float) as tempo,

        -- Performance metrics
        cast(stream_count as bigint) as stream_count,

        -- Flags
        case
            when explicit = 1 then true
            else false
        end as is_explicit

    from source
)

select * from cleaned
