"""Render reconciliation results to the committed output artifacts.

Three files, all deterministic on the offline path: no wall-clock
timestamps, LF line endings, fixed column order, fixed float formatting.
The as-of dates that appear come from the fixtures, never from the machine
running the code, so a fresh offline run reproduces the committed outputs
byte for byte.
"""

import csv
import json

CSV_FIELDS = [
    "ticker",
    "metric",
    "period",
    "resolved_value",
    "resolved_source",
    "resolved_tier",
    "n_sources",
    "classification",
    "rel_disagreement_pct",
    "regulatory_anchor",
]

DETAIL_SECTIONS = [
    ("unit_scale_mismatch", "Unit-scale mismatches"),
    ("period_misalignment", "Period misalignment"),
    ("material_divergence", "Material divergence"),
    ("minor_divergence", "Minor divergence"),
    ("single_source", "Single-source groups"),
]


def fmt_value(metric: str, value: float) -> str:
    if metric == "eps_diluted":
        return f"{value:,.2f}"
    return f"{value:,.0f}"


def write_resolved_csv(reconciled, path):
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=CSV_FIELDS, lineterminator="\n")
        writer.writeheader()
        for g in reconciled:
            writer.writerow({
                "ticker": g.ticker,
                "metric": g.metric,
                "period": g.period,
                "resolved_value": (
                    f"{g.resolved_value:.2f}" if g.metric == "eps_diluted"
                    else f"{g.resolved_value:.0f}"
                ),
                "resolved_source": g.resolved_source,
                "resolved_tier": g.resolved_tier,
                "n_sources": g.n_sources,
                "classification": g.classification,
                "rel_disagreement_pct": f"{g.rel_disagreement_pct:.4f}",
                "regulatory_anchor": int(g.regulatory_anchor),
            })


def write_metrics_json(summary, path):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(summary, f, indent=2)
        f.write("\n")


def _group_detail(g):
    lines = [
        f"### {g.ticker} {g.metric} {g.period}",
        "",
        "| source | value | window end |",
        "|---|---|---|",
    ]
    for s in sorted(g.values):
        lines.append(
            f"| {s} | {fmt_value(g.metric, g.values[s])} | {g.period_ends[s]} |"
        )
    lines.append("")
    if g.classification == "single_source":
        lines.append(f"{g.note}.")
    else:
        lines.append(
            f"Relative disagreement {g.rel_disagreement_pct:,.2f}%. "
            f"Resolved to {g.resolved_source} ({g.resolved_tier}): "
            f"{fmt_value(g.metric, g.resolved_value)}."
            + (f" Note: {g.note}." if g.note else "")
        )
    lines.append("")
    return lines


def render_disagreement_report(reconciled, summary) -> str:
    s = summary
    lines = [
        "# Disagreement Report",
        "",
        "Generated by run_all.py. Groups are (company, metric, fiscal period); "
        "each is measured for cross-source disagreement before resolution "
        "through the source-reliability hierarchy "
        "(regulatory > commercial > derived).",
        "",
        "## Summary",
        "",
        f"- Companies: {s['companies']}",
        f"- Sources: {', '.join(s['sources'])}",
        f"- Observations: {s['observations']}",
        f"- Reconciliation groups: {s['groups']}",
        f"- Clean agreement (spread <= 0.5% of median): "
        f"{s['classification']['agreement']} groups "
        f"({s['agreement_rate_pct']:.1f}%)",
        f"- Groups resolved without a regulatory anchor: "
        f"{s['groups_without_regulatory_anchor']}",
        "",
        "| classification | groups |",
        "|---|---|",
    ]
    for cls, count in s["classification"].items():
        lines.append(f"| {cls} | {count} |")
    lines.append("")

    by_class = {}
    for g in reconciled:
        by_class.setdefault(g.classification, []).append(g)

    for cls, title in DETAIL_SECTIONS:
        groups = by_class.get(cls, [])
        if not groups:
            continue
        lines.append(f"## {title} ({len(groups)})")
        lines.append("")
        for g in groups:
            lines.extend(_group_detail(g))

    no_anchor = [g for g in reconciled if not g.regulatory_anchor]
    if no_anchor:
        lines.append("## Resolved without a regulatory anchor")
        lines.append("")
        lines.append(
            "These groups had no regulatory source covering the period, so "
            "the resolved value rests on vendor data alone:"
        )
        lines.append("")
        for g in no_anchor:
            lines.append(
                f"- {g.ticker} {g.metric} {g.period}: resolved from "
                f"{g.resolved_source} ({g.classification})"
            )
        lines.append("")
    return "\n".join(lines)


def write_disagreement_report(reconciled, summary, path):
    text = render_disagreement_report(reconciled, summary)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
        if not text.endswith("\n"):
            f.write("\n")
