"""Execute sql/analysis.sql against a pipeline store and render the report.

Mirrors the sibling project's SQL layer: every statement in the file runs in
order, results print to the console, and outputs/sql_report.md is written so
the analysis is inspectable without running anything.
"""

from pathlib import Path

import duckdb

PROJECT_ROOT = Path(__file__).resolve().parents[1]
ANALYSIS_SQL = PROJECT_ROOT / "sql" / "analysis.sql"

TITLES = [
    "Coverage by source",
    "Coverage gaps by metric",
    "Disagreement leaderboard (flagged groups, worst first)",
    "Classification mix",
    "Resolved fundamentals, latest fiscal year (USD millions except eps)",
    "Resolution provenance",
]


def _statements(sql_path):
    # Strip full-line comments before splitting so a semicolon inside a
    # comment can never shear a statement in half.
    text = "\n".join(
        line for line in Path(sql_path).read_text(encoding="utf-8").splitlines()
        if not line.lstrip().startswith("--")
    )
    return [s.strip() for s in text.split(";") if s.strip()]


def _cell(value) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, float):
        return f"{value:g}"
    return str(value)


def render_table(columns, rows) -> str:
    """Plain-text table, sized by content only.

    DuckDB's own relation rendering adapts column widths to the detected
    terminal, which would make the committed report depend on where it was
    generated. This renderer is a pure function of the data.
    """
    cells = [[_cell(v) for v in row] for row in rows]
    widths = [
        max(len(col), *(len(r[i]) for r in cells)) if cells else len(col)
        for i, col in enumerate(columns)
    ]
    def fmt(row):
        return "| " + " | ".join(v.ljust(widths[i]) for i, v in enumerate(row)) + " |"
    lines = [fmt(list(columns))]
    lines.append("|" + "|".join("-" * (w + 2) for w in widths) + "|")
    lines.extend(fmt(r) for r in cells)
    lines.append(f"({len(cells)} rows)")
    return "\n".join(lines)


def run_sql(db_path, out_path, sql_path=ANALYSIS_SQL, echo=True):
    """Run every statement in sql_path against db_path; write out_path."""
    con = duckdb.connect(str(db_path), read_only=True)
    lines = [
        "# SQL Analysis Report",
        "",
        "Generated by sql/run_sql.py (DuckDB) over the pipeline store built "
        "from schema.sql.",
        "",
    ]
    try:
        for i, stmt in enumerate(_statements(sql_path)):
            title = TITLES[i] if i < len(TITLES) else f"Query {i + 1}"
            rel = con.sql(stmt)
            table = render_table(rel.columns, rel.fetchall())
            if echo:
                print(f"\n== {title} ==\n{table}")
            lines.append(f"## {i + 1}. {title}")
            lines.append("")
            lines.append("```")
            lines.append(table.rstrip())
            lines.append("```")
            lines.append("")
    finally:
        con.close()
    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    return out_path
