"""Execute the analytical SQL against the pipeline outputs with DuckDB.

Reads outputs/resolved.csv and data/labels.csv as views, runs every
statement in analysis.sql, prints the results, and writes
outputs/sql_report.md so the analysis is inspectable without running
anything.
"""

import sys
from pathlib import Path

import duckdb

# DuckDB renders tables with box-drawing characters; legacy Windows consoles
# default to cp1252 and crash on them.
if sys.stdout.encoding and sys.stdout.encoding.lower() not in ("utf-8", "utf8"):
    sys.stdout.reconfigure(encoding="utf-8")

ROOT = Path(__file__).resolve().parent.parent
SQL = Path(__file__).resolve().parent / "analysis.sql"

TITLES = [
    "Top vendors by resolved spend",
    "Category concentration (top-3 vendor share)",
    "Weekly resolution mix and week-over-week delta",
    "New-vendor candidates ranked by spend at stake",
    "Pipeline precision by week (vs ground truth)",
]


def main() -> None:
    con = duckdb.connect()
    con.execute(f"CREATE VIEW resolved AS SELECT * FROM read_csv_auto('{ROOT / 'outputs' / 'resolved.csv'}')")
    con.execute(f"CREATE VIEW labels AS SELECT * FROM read_csv_auto('{ROOT / 'data' / 'labels.csv'}')")

    # strip full-line comments before splitting so a semicolon inside a
    # comment can never shear a statement in half
    sql_text = "\n".join(
        line for line in SQL.read_text(encoding="utf-8").splitlines()
        if not line.lstrip().startswith("--")
    )
    statements = [s.strip() for s in sql_text.split(";") if s.strip()]
    lines = ["# SQL Analysis Report", "",
             "Generated by sql/run_sql.py (DuckDB) over outputs/resolved.csv.", ""]
    for i, stmt in enumerate(statements):
        title = TITLES[i] if i < len(TITLES) else f"Query {i + 1}"
        rel = con.sql(stmt)
        table = str(rel)
        print(f"\n== {title} ==\n{table}")
        lines.append(f"## {i + 1}. {title}")
        lines.append("")
        lines.append("```")
        lines.append(table.rstrip())
        lines.append("```")
        lines.append("")
    (ROOT / "outputs" / "sql_report.md").write_text("\n".join(lines), encoding="utf-8")
    print("\nwrote outputs/sql_report.md")


if __name__ == "__main__":
    main()
