"""Writes outputs/readiness_report.md from the computed output tables.

Descriptive only. The scored comparison of readiness against MLB outcomes
(the grading layer) is deliberately not built yet, by the owner's
sequencing decision, and nothing in this report computes a hit rate or an
accuracy claim. The counts that touch debut status are labeled as
description, not evaluation.

Scoped to hitters only as of 2026-08-02; see the project README.
"""

import csv
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import config


def read_csv(path):
    with open(path, encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def main():
    summary = read_csv(config.OUTPUTS / "readiness_summary.csv")
    seasons = read_csv(config.OUTPUTS / "readiness_by_season.csv")
    stints = read_csv(config.OUTPUTS / "readiness_stints.csv")
    calib = read_csv(config.OUTPUTS / "calibration_table.csv")
    metrics = json.loads((config.DATA_DERIVED / "crosswalk_metrics.json").read_text())

    debuted = [s for s in summary if s["mlb_debut_date"]]
    never = [s for s in summary if not s["mlb_debut_date"]]
    crossed = [s for s in summary if s["first_crossing_season"]]
    base_crossed = [s for s in summary if s["first_base_crossing_season"]]

    scored_rows = [r for r in seasons if r["verdict"] == "scored"]
    refused = [r for r in seasons if r["verdict"] != "scored"]

    # Age-credit dominance, measured not asserted.
    mean_base = sum(float(r["base_war"]) for r in scored_rows) / len(scored_rows)
    mean_credit = sum(float(r["age_credit_war"]) for r in scored_rows) / len(scored_rows)
    crossing_rows = [r for r in scored_rows if float(r["adj_war"]) > 0]
    credit_only = [r for r in crossing_rows if float(r["base_war"]) <= 0]

    # First-crossing level distribution: dominant level (by volume) of each
    # player's first crossing season.
    stints_by = defaultdict(list)
    for st in stints:
        stints_by[(st["mlbam_id"], st["season"])].append(st)
    level_dist = Counter()
    for s in crossed:
        rows = [r for r in stints_by.get((s["mlbam_id"], s["first_crossing_season"]), [])
                if r["verdict"] == "scored"]
        if rows:
            level_dist[max(rows, key=lambda r: float(r["pa"] or 0))["level"]] += 1

    def by_rate(rows):
        out = [r for r in rows if r["debut_day_rate_per_600"] not in ("", None)]
        return sorted(out, key=lambda r: float(r["debut_day_rate_per_600"]), reverse=True)

    lines = []
    w = lines.append
    w("# Readiness report")
    w("")
    w("Generated by scripts/write_report.py from the generated output tables.")
    w("Descriptive only. The scored comparison against MLB outcomes is")
    w("deliberately not built yet, by the owner's sequencing decision. No")
    w("number below is an accuracy claim.")
    w("")
    w("## Population")
    w("")
    w(f"- {metrics['ranking_rows']} ranking rows, {metrics['matched_rows']} matched "
      f"({metrics['coverage_pct']}%), {metrics['unique_matched_players']} unique players")
    w(f"- Match stages: {metrics['by_stage']}. The manual_override stage is two "
      f"curated name-collision resolutions with written provenance in "
      f"data/raw/manual_overrides.csv, kept out of the matcher's earned accuracy.")
    w(f"- {len(debuted)} players have debuted in MLB, {len(never)} have not")
    w("")
    w("## Readiness, descriptive counts")
    w("")
    w(f"- {len(base_crossed)} of {len(summary)} crossed zero on base production "
      f"alone, {len(crossed)} with the age credit included "
      f"({len(crossed) - len(base_crossed)} players cross only via the credit)")
    w(f"- First-crossing dominant level: {dict(level_dist.most_common())}")
    w(f"- Across {len(scored_rows)} scored player-seasons, the age credit "
      f"averages {mean_credit:.2f} wins against {mean_base:.2f} wins of base "
      f"signal, and {len(credit_only)} of {len(crossing_rows)} crossing "
      f"seasons ({100 * len(credit_only) / len(crossing_rows):.0f}%) cross on "
      f"the credit alone. The credit, not the translation factor, is the "
      f"dominant source of generosity, which is why it ships severable.")
    w("- For a Top-100 population these crossing rates are not absurd on")
    w(f"  their face ({len(debuted)} of {len(summary)} really did reach MLB), but")
    w("  whether crossing predicted anything is exactly what the deferred")
    w("  grading layer will test. These are counts, not a hit rate.")
    w("")
    basis = Counter(s["debut_reading_basis"].split("_over_")[0] for s in debuted)
    w(f"- Debut-day reading basis across debuted players: {dict(basis.most_common())}")
    w(f"- Season readings refused for sample size: {len(refused)} of "
      f"{len(seasons)} ({len(scored_rows)} scored)")
    w("")
    w("## Two scores, not one: Readiness Score and Rate Score")
    w("")
    w("Per Reid's ruling 2026-08-01. Readiness Score is total value banked by")
    w("debut day, how much he'd already proven, naturally larger the more he")
    w("played before getting called up. Rate Score restates the same")
    w("performance as if he'd gotten a full 600-PA season, how good he was")
    w("per opportunity, independent of how much opportunity he actually got.")
    w("They can disagree sharply for a player with a short but excellent")
    w("pre-debut window: a small sample caps how much total value there is")
    w("to bank, even when the quality per plate appearance was elite. Neither")
    w("number is the real one. They answer different questions.")
    w("")
    w("**Top 15 by Rate Score:**")
    w("")
    w("| Player | Pos | Debut | Rate Score | Readiness Score (base / adj) | Basis |")
    w("|---|---|---|---|---|---|")
    for s in by_rate(debuted)[:15]:
        w(f"| {s['player']} | {s['position']} | {s['mlb_debut_date']} | "
          f"{s['debut_day_rate_per_600']} | "
          f"{s['debut_day_base_war']} / {s['debut_day_adj_war']} | "
          f"{s['debut_reading_basis']} |")
    w("")
    w("## Calibration, what a dead-average regular scores under this chain")
    w("")
    w("The known generosity of a production-only score shows up here rather")
    w("than being hidden. Zero is the claim under test, not a settled truth.")
    w("The blended columns restate the factors against a blended-MLB baseline")
    w("(divided by 1.05), the sensitivity promised in the spec.")
    w("")
    w("| Level | Season | Avg hitter /600 PA | Hitter (blended) |")
    w("|---|---|---|---|")
    for c in calib:
        w(f"| {c['level']} | {c['season']} | {c['avg_hitter_war_per_600pa']} | "
          f"{c['avg_hitter_war_per_600pa_blended']} |")
    w("")
    w("## Disclosures")
    w("")
    w("1. Production only. Defense, park effects, and baserunning beyond")
    w("   steals are excluded, so the score systematically flatters bat-first")
    w("   prospects and understates glove-first ones.")
    w("2. The age credit is the dominant source of generosity, measured above,")
    w("   not the translation factors. It is a predictive-weight equivalence")
    w("   (Stoltz 2022), larger than what open-source implementations use, and")
    w("   it ships as its own severable column everywhere.")
    w("3. Translation factors are 2016-vintage Davenport estimates applied as")
    w("   level tiers. Triple-A's current inflated run environment makes AAA")
    w("   readings generous, visible in the calibration table.")
    w("4. Dominican Summer League stints are excluded from scoring. No cited")
    w("   translation factor covers the DSL, and the rookie-level age baseline")
    w("   pools it with US complex ball, which let DSL teenagers max the age")
    w("   cap against leagues they never played in.")
    w("5. The positional adjustment uses the position on the player's earliest")
    w("   ranking-list row (pre-debut vintage), because the API's position")
    w("   label is current-day even in historical payloads. The cost is coarse")
    w("   buckets (INF, OF) with in-house averaged constants.")
    w("6. The player's own inputs are strictly pre-debut. League baselines and")
    w("   level average ages are full-season aggregates, per the season-totals")
    w("   design ruling, so debut-day readings use season-level league context")
    w("   that finished forming after the debut. Disclosed, not hidden.")
    w("7. wOBA weights are one MLB season's constants (2023, scale 1.204)")
    w("   applied across all levels and seasons.")
    w("8. Scoped to hitters only as of 2026-08-02. Pitcher evaluation needs a")
    w("   different WAR construction, validated against real published")
    w("   research, and is being developed separately, not abandoned; see the")
    w("   project README.")
    w("")

    path = config.OUTPUTS / "readiness_report.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
